@extends('layouts.app')
@section('title', __('Edit User'))
@section('content')
<div class="mx-auto max-w-3xl p-4 sm:p-6 lg:p-8"><div class="mb-6"><h2 class="text-xl font-semibold text-ink">{{ __('Edit User') }}</h2><p class="mt-1 text-sm text-ink-secondary">{{ __('Update account information, status, and roles') }}</p></div>
<form method="POST" action="{{ route('users.update', $user) }}" class="card-institutional space-y-6 p-6">@csrf @method('PUT')
<div><label for="name" class="mb-1 block text-sm font-medium text-ink">{{ __('Name') }}</label><input id="name" name="name" value="{{ old('name', $user->name) }}" required class="input-institutional w-full text-sm">@error('name')<p class="mt-1 text-sm text-danger">{{ $message }}</p>@enderror</div>
<div><label for="email" class="mb-1 block text-sm font-medium text-ink">{{ __('Email') }}</label><input id="email" type="email" name="email" value="{{ old('email', $user->email) }}" required class="input-institutional w-full text-sm" dir="ltr">@error('email')<p class="mt-1 text-sm text-danger">{{ $message }}</p>@enderror</div>
<div><label class="mb-2 block text-sm font-medium text-ink">{{ __('Roles') }}</label><div class="grid gap-2 sm:grid-cols-2">@php($selectedRoles = old('roles', $user->roles->pluck('name')->all()))@foreach($roles as $role)<label class="flex items-center gap-2 border border-border p-3"><input type="checkbox" name="roles[]" value="{{ $role->name }}" @checked(in_array($role->name, $selectedRoles, true)) class="h-4 w-4 rounded border-border-strong text-brand-600"><span class="text-sm text-ink">{{ __('messages.roles.'.$role->name) }}</span></label>@endforeach</div>@error('roles')<p class="mt-1 text-sm text-danger">{{ $message }}</p>@enderror</div>
<label class="flex items-center gap-2"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $user->is_active)) class="h-4 w-4 rounded border-border-strong text-brand-600"><span class="text-sm text-ink-secondary">{{ __('Active') }}</span></label>@error('is_active')<p class="text-sm text-danger">{{ $message }}</p>@enderror
div class="flex justify-end gap-3 border-t border-border pt-5"><a href="{{ route('users.show', $user) }}" class="rounded-md border border-border-strong bg-white px-4 py-2 text-sm font-medium text-ink hover:bg-surface-1">{{ __('Cancel') }}</a><button type="submit" class="rounded-md bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700">{{ __('Save Changes') }}</button></div>
</form></div>
@endsection