@extends('layouts.app')
@section('title', __('User Details'))
@section('content')
<div class="mx-auto max-w-6xl p-4 sm:p-6 lg:p-8">
    <div class="mb-6 flex flex-wrap items-center justify-between gap-4">
        <div><h2 class="text-xl font-semibold text-ink">{{ __('User Details') }}</h2><p class="mt-1 text-sm text-ink-secondary">{{ __('Account information and assigned roles') }}</p></div>
        <div class="flex gap-3">
            @can('users.update')<a href="{{ route('users.edit', $user) }}" class="rounded-md bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700">{{ __('Edit') }}</a>@endcan
            <a href="{{ route('users.index') }}" class="rounded-md border border-border-strong bg-white px-4 py-2 text-sm font-medium text-ink hover:bg-surface-1">{{ __('Back to Users') }}</a>
        </div>
    </div>
    <div class="grid gap-6 lg:grid-cols-2">
        <div class="card-institutional p-6"><h3 class="mb-5 text-base font-semibold text-ink">{{ __('Account') }}</h3><dl class="space-y-4"><div><dt class="text-sm text-ink-muted">{{ __('Name') }}</dt><dd class="mt-1 text-sm font-medium text-ink">{{ $user->name }}</dd></div><div><dt class="text-sm text-ink-muted">{{ __('Email') }}</dt><dd class="ltr-value mt-1 text-sm font-medium text-ink">{{ $user->email }}</dd></div><div><dt class="text-sm text-ink-muted">{{ __('Status') }}</dt><dd class="mt-1"><span class="inline-flex rounded-md border px-2 py-0.5 text-xs font-medium {{ $user->is_active ? 'border-success bg-success-surface text-success' : 'border-border bg-surface-1 text-ink-muted' }}">{{ $user->is_active ? __('Active') : __('Inactive') }}</span></dd></div><div><dt class="text-sm text-ink-muted">{{ __('Last Login') }}</dt><dd class="ltr-value mt-1 text-sm text-ink">{{ $user->last_login_at?->format('Y-m-d H:i') ?? '—' }}</dd></div><div><dt class="text-sm text-ink-muted">{{ __('Created At') }}</dt><dd class="ltr-value mt-1 text-sm text-ink">{{ $user->created_at?->format('Y-m-d H:i') ?? '—' }}</dd></div></dl></div>
        <div class="card-institutional p-6"><h3 class="mb-5 text-base font-semibold text-ink">{{ __('Assigned Roles') }}</h3>@if($user->roles->isEmpty())<p class="text-sm text-ink-muted">{{ __('No roles assigned.') }}</p>@else<div class="space-y-4">@foreach($user->roles as $role)<div class="border border-border p-4"><div class="flex items-center justify-between gap-3"><span class="font-medium text-ink">{{ __('messages.roles.'.$role->name) }}</span><span class="text-xs text-ink-muted">{{ $role->permissions->count() }} {{ __('permissions') }}</span></div>@if($role->permissions->isNotEmpty())<div class="mt-3 flex flex-wrap gap-1.5">@foreach($role->permissions as $permission)<span class="inline-flex border border-border bg-surface-1 px-2 py-0.5 font-mono text-xs text-ink-secondary" dir="ltr">{{ $permission->name }}</span>@endforeach</div>@endif</div>@endforeach</div>@endif</div>
        <div class="card-institutional p-6 lg:col-span-2"><div class="mb-4"><h3 class="text-base font-semibold text-ink">{{ __('Custom Account Permissions') }}</h3><p class="mt-1 text-sm text-ink-secondary">{{ __('Permissions assigned directly to this account, separate from role permissions.') }}</p></div>@if($user->permissions->isEmpty())<p class="text-sm text-ink-muted">{{ __('No custom permissions assigned.') }}</p>@else<div class="flex flex-wrap gap-2">@foreach($user->permissions as $permission)<span class="inline-flex rounded-md border border-border bg-surface-1 px-2 py-1 text-xs font-medium text-ink-secondary"><span class="me-2">{{ __('messages.permissions.'.$permission->name) }}</span><code class="ltr-value">{{ $permission->name }}</code></span>@endforeach</div>@endif</div>
    </div>
</div>
@endsection
