@extends('layouts.app')
@section('title', 'تفاصيل المهمة')
@section('content')
<div class="mx-auto max-w-6xl p-4 sm:p-6 lg:p-8">
@php $statusLabels=['pending'=>'معلقة','assigned'=>'مسندة','in_progress'=>'قيد التنفيذ','completed'=>'مكتملة','cancelled'=>'ملغاة']; $priorityLabels=['low'=>'منخفضة','medium'=>'متوسطة','high'=>'عالية','urgent'=>'عاجلة']; $priorityClasses=['low'=>'border-border bg-surface-1 text-ink-secondary','medium'=>'border-info bg-info-surface text-info','high'=>'border-warning bg-warning-surface text-warning','urgent'=>'border-danger bg-danger-surface text-danger']; @endphp
<div class="mb-6 flex flex-wrap items-start justify-between gap-4"><div><div class="mb-2 flex items-center gap-3"><code class="ltr-value text-sm font-semibold text-brand-600">{{ $workOrder->work_order_number }}</code><span class="inline-flex rounded-md border border-border bg-surface-1 px-2 py-1 text-xs font-medium text-ink-secondary">{{ $statusLabels[$workOrder->status] ?? $workOrder->status }}</span></div><h2 class="text-xl font-semibold text-ink">{{ $workOrder->title }}</h2><p class="mt-1 text-sm text-ink-secondary">تفاصيل المهمة والشكاوى المرتبطة بها.</p></div><div class="flex gap-2">
@canany(['reports.export','tasks.export'])<a href="{{ route('reports.work-orders.pdf', $workOrder) }}" class="rounded-md border border-border-strong bg-white px-4 py-2 text-sm font-medium text-ink hover:bg-surface-1">تقرير PDF</a>@endcan<a href="{{ route('work-orders.index') }}" class="rounded-md border border-border-strong bg-white px-4 py-2 text-sm font-medium text-ink hover:bg-surface-1">العودة إلى المهام</a>@can('tasks.delete')<form method="POST" action="{{ route('work-orders.destroy',$workOrder) }}" onsubmit="return confirm('هل تريد حذف هذه المهمة؟');">@csrf @method('DELETE')<button class="rounded-md border border-danger bg-white px-4 py-2 text-sm font-medium text-danger hover:bg-danger-surface">حذف المهمة</button></form>@endcan</div></div>
@if($errors->any())<div class="mb-5 rounded-md border border-danger bg-danger-surface p-4 text-sm text-danger">{{ $errors->first() }}</div>@endif
<div class="grid gap-5 lg:grid-cols-3"><section class="card-institutional p-5 lg:col-span-2"><h3 class="mb-4 text-base font-semibold text-ink">بيانات المهمة</h3><dl class="grid gap-4 sm:grid-cols-2"><div><dt class="text-xs text-ink-muted">العنوان</dt><dd class="mt-1 text-sm font-medium text-ink">{{ $workOrder->title }}</dd></div><div><dt class="text-xs text-ink-muted">المسند إليه</dt><dd class="mt-1 text-sm text-ink">{{ $workOrder->assignedTo->name ?? 'غير مسندة' }}</dd></div><div><dt class="text-xs text-ink-muted">الأولوية</dt><dd class="mt-1"><span class="inline-flex rounded-md border px-2 py-1 text-xs font-medium {{ $priorityClasses[$workOrder->priority] ?? $priorityClasses['medium'] }}">{{ $priorityLabels[$workOrder->priority] ?? $workOrder->priority }}</span></dd></div><div><dt class="text-xs text-ink-muted">أنشأها</dt><dd class="mt-1 text-sm text-ink">{{ $workOrder->createdBy->name ?? '—' }}</dd></div><div class="sm:col-span-2"><dt class="text-xs text-ink-muted">الوصف</dt><dd class="mt-1 whitespace-pre-line text-sm leading-7 text-ink">{{ $workOrder->description ?: '—' }}</dd></div><div><dt class="text-xs text-ink-muted">بدأت</dt><dd class="mt-1 text-sm text-ink ltr-value">{{ $workOrder->started_at?->format('Y-m-d H:i') ?? '—' }}</dd></div><div><dt class="text-xs text-ink-muted">اكتملت</dt><dd class="mt-1 text-sm text-ink ltr-value">{{ $workOrder->completed_at?->format('Y-m-d H:i') ?? '—' }}</dd></div><div class="sm:col-span-2"><dt class="text-xs text-ink-muted">موقع المهمة</dt><dd class="mt-1 text-sm text-ink ltr-value">{{ $workOrder->latitude !== null && $workOrder->longitude !== null ? $workOrder->latitude . ', ' . $workOrder->longitude : 'يتم استخدام موقع الشكوى المرتبطة إن وجد' }}</dd></div><div class="sm:col-span-2"><dt class="text-xs text-ink-muted">ملاحظات</dt><dd class="mt-1 whitespace-pre-line text-sm leading-7 text-ink">{{ $workOrder->notes ?: '—' }}</dd></div></dl></section>
@canany(['tasks.update','tasks.assign','tasks.transition'])<section class="card-institutional p-5"><h3 class="mb-4 text-base font-semibold text-ink">تحديث المهمة</h3><form method="POST" action="{{ route('work-orders.update',$workOrder) }}" class="space-y-4">@csrf @method('PUT')
@can('tasks.transition')<div><label for="status" class="mb-1 block text-sm font-medium text-ink">الحالة</label><select id="status" name="status" class="input-institutional w-full text-sm" required>@foreach($statusLabels as $value=>$label)<option value="{{ $value }}" @selected($workOrder->status===$value)>{{ $label }}</option>@endforeach</select></div>@endcan
@can('tasks.assign')<div><label for="assigned_to" class="mb-1 block text-sm font-medium text-ink">المسند إليه</label><select id="assigned_to" name="assigned_to" class="input-institutional w-full text-sm"><option value="">غير مسندة</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected($workOrder->assigned_to===$user->id)>{{ $user->name }}</option>@endforeach</select></div>@endcan
@can('tasks.update')<div><label for="priority" class="mb-1 block text-sm font-medium text-ink">الأولوية</label><select id="priority" name="priority" class="input-institutional w-full text-sm">@foreach($priorityLabels as $value=>$label)<option value="{{ $value }}" @selected($workOrder->priority===$value)>{{ $label }}</option>@endforeach</select></div><div><label for="notes" class="mb-1 block text-sm font-medium text-ink">ملاحظات</label><textarea id="notes" name="notes" rows="4" class="input-institutional w-full text-sm">{{ old('notes',$workOrder->notes) }}</textarea></div><div><label class="mb-2 block text-sm font-medium text-ink">موقع المهمة</label><div class="mb-3 flex justify-end"><button type="button" data-location-picker data-latitude-field="latitude" data-longitude-field="longitude" class="rounded-md border border-brand-600 bg-white px-3 py-2 text-sm font-medium text-brand-700">تحديد الموقع من الخريطة</button></div><div class="grid gap-3 grid-cols-2"><div><label for="latitude" class="mb-1 block text-xs text-ink-secondary">خط العرض</label><input id="latitude" name="latitude" value="{{ old('latitude',$workOrder->latitude) }}" type="number" step="any" min="-90" max="90" class="input-institutional w-full text-sm"></div><div><label for="longitude" class="mb-1 block text-xs text-ink-secondary">خط الطول</label><input id="longitude" name="longitude" value="{{ old('longitude',$workOrder->longitude) }}" type="number" step="any" min="-180" max="180" class="input-institutional w-full text-sm"></div></div></div>@endcan
<button class="w-full rounded-md bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700">حفظ التعديلات</button></form></section>@endcanany</div>
@php $linkedGisIds = collect($gisContext['linked'] ?? [])->pluck('id')->all(); @endphp
<section class="card-institutional mt-5 p-5">
<div class="flex flex-wrap items-center justify-between gap-3"><div><h3 class="text-base font-semibold text-ink">السياق المكاني</h3><p class="mt-1 text-sm text-ink-secondary">الأصول المكانية المرتبطة بالمهمة وأقرب الأصول التشغيلية إلى موقعها.</p></div>@if($gisContext['latitude'] !== null && $gisContext['longitude'] !== null)<span class="text-xs text-ink-muted ltr-value">{{ $gisContext['latitude'] }}, {{ $gisContext['longitude'] }}</span>@endif</div>
<div class="mt-5 grid gap-5 lg:grid-cols-2">
<div><h4 class="mb-3 text-sm font-semibold text-ink">الأصول المرتبطة</h4>
@if(!empty($gisContext['linked']))<div class="space-y-2">@foreach($gisContext['linked'] as $feature)<div class="flex items-center justify-between gap-3 rounded-md border border-border bg-surface-1 p-3"><div><div class="text-sm font-medium text-ink">{{ $feature['dataset_name'] }}</div><div class="mt-1 text-xs text-ink-muted">{{ $feature['identifier'] ?: 'Feature #'.$feature['id'] }} · {{ $feature['geometry_type'] }}</div></div>@can('tasks.update')<form method="POST" action="{{ route('work-orders.gis.unlink', [$workOrder, $feature['id']]) }}" onsubmit="return confirm('إلغاء ربط هذا الأصل؟');">@csrf @method('DELETE')<button class="text-xs font-medium text-danger">إلغاء الربط</button></form>@endcan</div>@endforeach</div>
@else<p class="rounded-md border border-dashed border-border p-4 text-sm text-ink-muted">لا توجد أصول مكانية مرتبطة حاليًا.</p>@endif</div>
<div><h4 class="mb-3 text-sm font-semibold text-ink">أقرب الأصول التشغيلية</h4>
@if(!empty($gisContext['nearest']))<div class="space-y-2">@foreach($gisContext['nearest'] as $feature)<div class="flex items-center justify-between gap-3 rounded-md border border-border p-3"><div><div class="text-sm font-medium text-ink">{{ $feature['dataset_name'] }}</div><div class="mt-1 text-xs text-ink-muted">{{ $feature['identifier'] ?: 'Feature #'.$feature['id'] }} · {{ number_format($feature['distance_m'], 2) }} م</div></div>@if(in_array($feature['id'], $linkedGisIds, true))<span class="text-xs font-medium text-success">مرتبط</span>@else@can('tasks.update')<form method="POST" action="{{ route('work-orders.gis.link', [$workOrder, $feature['id']]) }}">@csrf<button class="rounded-md border border-brand-600 bg-white px-3 py-1.5 text-xs font-medium text-brand-700 hover:bg-surface-1">ربط</button></form>@endcan@endif</div>@endforeach</div>
@else<p class="rounded-md border border-dashed border-border p-4 text-sm text-ink-muted">لا يوجد موقع جغرافي صالح للبحث عن أقرب أصل.</p>@endif</div></div></section>
<section class="card-institutional mt-5 overflow-hidden"><div class="border-b border-border px-5 py-4"><h3 class="text-base font-semibold text-ink">الشكاوى المرتبطة</h3><p class="mt-1 text-sm text-ink-secondary">{{ $workOrder->complaints->count() }} شكوى مرتبطة بهذه المهمة. عند إكمال المهمة يتم إغلاق الشكاوى المرتبطة تلقائيًا.</p></div><div class="overflow-x-auto"><table class="table-institutional"><thead><tr><th>رقم الشكوى</th><th>العنوان</th><th>المسند إليه</th><th>الحالة</th><th>الأولوية</th><th>الإجراء</th></tr></thead><tbody>@forelse($workOrder->complaints as $complaint)<tr><td><code class="ltr-value text-sm font-medium text-ink">{{ $complaint->complaint_number }}</code></td><td>{{ $complaint->title }}</td><td>{{ $complaint->assignedTo->name ?? 'غير مسندة' }}</td><td>{{ ['open'=>'جديدة','in_progress'=>'قيد المعالجة','resolved'=>'تم الحل','closed'=>'مغلقة','cancelled'=>'ملغاة'][$complaint->status] ?? $complaint->status }}</td><td>{{ $priorityLabels[$complaint->priority] ?? $complaint->priority }}</td><td><a href="{{ route('complaints.show',$complaint) }}" class="text-sm font-medium text-brand-600">عرض الشكوى</a></td></tr>@empty<tr><td colspan="6" class="py-10 text-center text-sm text-ink-muted">لا توجد شكاوى مرتبطة بهذه المهمة.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
