@extends('layouts.app')
@section('title', 'تسجيل شكوى')
@section('content')
<div class="mx-auto max-w-5xl p-4 sm:p-6 lg:p-8"><div class="mb-6"><h2 class="text-xl font-semibold text-ink">تسجيل شكوى جديدة</h2><p class="mt-1 text-sm text-ink-secondary">أدخل بيانات المشكلة وموقعها ليتم متابعتها من دائرة المياه.</p></div>
<form method="POST" action="{{ route('complaints.store') }}" class="card-institutional space-y-6 p-6">@csrf
<div class="grid gap-6 md:grid-cols-2"><div><label for="title" class="mb-1 block text-sm font-medium text-ink">عنوان المشكلة <span class="text-danger">*</span></label><input id="title" name="title" value="{{ old('title') }}" required class="input-institutional w-full text-sm"></div><div><label for="priority" class="mb-1 block text-sm font-medium text-ink">الأولوية</label><select id="priority" name="priority" class="input-institutional w-full text-sm"><option value="low">منخفضة</option><option value="medium" @selected(old('priority','medium')==='medium')>متوسطة</option><option value="high">عالية</option><option value="urgent">عاجلة</option></select></div></div>
<div><label for="description" class="mb-1 block text-sm font-medium text-ink">وصف المشكلة <span class="text-danger">*</span></label><textarea id="description" name="description" rows="4" required class="input-institutional w-full text-sm">{{ old('description') }}</textarea></div>
<div class="border-t border-border pt-6"><h3 class="mb-4 text-base font-semibold text-ink">بيانات المواطن</h3><div class="grid gap-6 md:grid-cols-2"><div><label for="contact_name" class="mb-1 block text-sm font-medium text-ink">اسم المواطن</label><input id="contact_name" name="contact_name" value="{{ old('contact_name') }}" class="input-institutional w-full text-sm"></div><div><label for="contact_phone" class="mb-1 block text-sm font-medium text-ink">رقم الهاتف</label><input id="contact_phone" name="contact_phone" value="{{ old('contact_phone') }}" class="input-institutional w-full text-sm" dir="ltr"></div><div class="md:col-span-2"><label for="address" class="mb-1 block text-sm font-medium text-ink">العنوان / وصف الموقع</label><textarea id="address" name="address" rows="2" class="input-institutional w-full text-sm">{{ old('address') }}</textarea></div></div></div>
<div class="border-t border-border pt-6"><h3 class="mb-1 text-base font-semibold text-ink">الموقع الجغرافي</h3><p class="mb-4 text-xs text-ink-muted">يمكن إدخال الإحداثيات يدوياً أو تحديد الموقع مباشرة من الخريطة.</p><div class="mb-4 flex justify-end"><button type="button" data-location-picker data-latitude-field="latitude" data-longitude-field="longitude" class="rounded-md border border-brand-600 bg-white px-3 py-2 text-sm font-medium text-brand-700">تحديد الموقع من الخريطة</button></div><div class="grid gap-6 md:grid-cols-2"><div><label for="latitude" class="mb-1 block text-sm font-medium text-ink">خط العرض Latitude</label><input id="latitude" name="latitude" value="{{ old('latitude') }}" type="number" step="any" min="-90" max="90" class="input-institutional w-full text-sm" dir="ltr"></div><div><label for="longitude" class="mb-1 block text-sm font-medium text-ink">خط الطول Longitude</label><input id="longitude" name="longitude" value="{{ old('longitude') }}" type="number" step="any" min="-180" max="180" class="input-institutional w-full text-sm" dir="ltr"></div></div></div>
@can('complaints.update')<div class="border-t border-border pt-6"><label for="assigned_to" class="mb-1 block text-sm font-medium text-ink">إسناد أولي للمسؤول</label><select id="assigned_to" name="assigned_to" class="input-institutional w-full text-sm"><option value="">بدون إسناد</option>@foreach($assignees as $assignee)<option value="{{ $assignee->id }}" @selected((string)old('assigned_to')===(string)$assignee->id)>{{ $assignee->name }} — {{ $assignee->email }}</option>@endforeach</select>@error('assigned_to')<p class="mt-1 text-sm text-danger">{{ $message }}</p>@enderror</div>@endcan
<div class="flex justify-end gap-3 border-t border-border pt-5"><a href="{{ route('complaints.index') }}" class="rounded-md border border-border-strong bg-white px-4 py-2 text-sm font-medium text-ink">إلغاء</a><button type="submit" class="rounded-md bg-brand-600 px-4 py-2 text-sm font-medium text-white">تسجيل الشكوى</button></div></form></div>
@endsection
