@extends('layouts.app')
@section('title', 'معالجة الشكوى')
@section('content')
<div class="mx-auto max-w-5xl p-4 sm:p-6 lg:p-8">
<div class="mb-6"><h2 class="text-xl font-semibold text-ink">معالجة الشكوى <code class="ltr-value text-sm text-brand-600">{{ $complaint->complaint_number }}</code></h2><p class="mt-1 text-sm text-ink-secondary">تظهر هنا فقط الإجراءات التي تسمح بها صلاحيات حسابك.</p></div>
<form method="POST" action="{{ route('complaints.update',$complaint) }}" class="card-institutional space-y-6 p-6">@csrf @method('PUT')
@can('complaints.update')
<div class="grid gap-6 md:grid-cols-2"><div><label for="title" class="mb-1 block text-sm font-medium text-ink">عنوان المشكلة</label><input id="title" name="title" value="{{ old('title',$complaint->title) }}" required class="input-institutional w-full text-sm"></div><div><label for="priority" class="mb-1 block text-sm font-medium text-ink">الأولوية</label><select id="priority" name="priority" class="input-institutional w-full text-sm"><option value="low" @selected(old('priority',$complaint->priority)==='low')>منخفضة</option><option value="medium" @selected(old('priority',$complaint->priority)==='medium')>متوسطة</option><option value="high" @selected(old('priority',$complaint->priority)==='high')>عالية</option><option value="urgent" @selected(old('priority',$complaint->priority)==='urgent')>عاجلة</option></select></div></div>
<div><label for="description" class="mb-1 block text-sm font-medium text-ink">وصف المشكلة</label><textarea id="description" name="description" rows="4" required class="input-institutional w-full text-sm">{{ old('description',$complaint->description) }}</textarea></div>
<div class="border-t border-border pt-6"><h3 class="mb-4 text-base font-semibold text-ink">الإسناد</h3><label for="assigned_to" class="mb-1 block text-sm font-medium text-ink">المسند إليه</label><select id="assigned_to" name="assigned_to" class="input-institutional w-full text-sm"><option value="">بدون إسناد</option>@foreach($assignees as $assignee)<option value="{{ $assignee->id }}" @selected((string)old('assigned_to',$complaint->assigned_to)===(string)$assignee->id)>{{ $assignee->name }} — {{ $assignee->email }}</option>@endforeach</select></div>
<div class="border-t border-border pt-6"><h3 class="mb-4 text-base font-semibold text-ink">المعالجة والحل</h3><div class="space-y-5"><div><label for="processing_notes" class="mb-1 block text-sm font-medium text-ink">إجراءات المعالجة والملاحظات</label><textarea id="processing_notes" name="processing_notes" rows="4" class="input-institutional w-full text-sm">{{ old('processing_notes',$complaint->processing_notes) }}</textarea></div><div><label for="solution" class="mb-1 block text-sm font-medium text-ink">الحل / نتيجة المعالجة</label><textarea id="solution" name="solution" rows="4" class="input-institutional w-full text-sm">{{ old('solution',$complaint->solution) }}</textarea></div></div></div>
@endcan
@can('complaints.transition')<div class="border-t border-border pt-6"><h3 class="mb-4 text-base font-semibold text-ink">الحالة</h3><select id="status" name="status" class="input-institutional w-full text-sm"><option value="open" @selected(old('status',$complaint->status)==='open')>جديدة</option><option value="in_progress" @selected(old('status',$complaint->status)==='in_progress')>قيد المعالجة</option><option value="resolved" @selected(old('status',$complaint->status)==='resolved')>تم الحل</option><option value="closed" @selected(old('status',$complaint->status)==='closed')>مغلقة</option><option value="cancelled" @selected(old('status',$complaint->status)==='cancelled')>ملغاة</option></select>@error('status')<p class="mt-1 text-sm text-danger">{{ $message }}</p>@enderror</div>@endcan
@canany(['complaints.update','complaints.transition'])<div class="flex justify-end gap-3 border-t border-border pt-5"><a href="{{ route('complaints.show',$complaint) }}" class="rounded-md border border-border-strong bg-white px-4 py-2 text-sm font-medium text-ink">إلغاء</a><button class="rounded-md bg-brand-600 px-4 py-2 text-sm font-medium text-white">حفظ التعديلات</button></div>@endcanany
</form></div>
@endsection
